#!/bin/sh -l

# Removing old dist folder
rm -rf dist/;
rm -rf zeta_cli.egg-info/;

# Uninstall a possible zeta-cli previous installed
pip3 uninstall zeta-cli -y

# Installing current Zeta-cli and running tests
python3 setup.py sdist bdist_wheel &&   \
    cd dist/ &&                         \
    pip3 install *.whl &&               \
    cd ../
