#!/bin/sh -l
cd tests/ &&                            \
    rm -rf build &&                     \
    west build -p auto -b native_posix &&       \
    west build -t run &&                \
    cd ../
