# ################################################################# #
#                      FILE GENERATED BY ZetaCLI                    #
#                         DON'T EDIT THIS FILE                      #
# ################################################################# #
message("[ZETA]: Running zeta.cmake")

execute_process(COMMAND zeta gen -b "${CMAKE_CURRENT_LIST_DIR}/build"
                        ${CMAKE_CURRENT_LIST_DIR}/zeta.yaml)

list(APPEND HEADERS "${CMAKE_CURRENT_LIST_DIR}/build/zeta/include/")
list(APPEND SOURCES "${CMAKE_CURRENT_LIST_DIR}/src/ping.c" "${CMAKE_CURRENT_LIST_DIR}/src/s02.c" "${CMAKE_CURRENT_LIST_DIR}/src/s03.c" "${CMAKE_CURRENT_LIST_DIR}/src/s04.c" "${CMAKE_CURRENT_LIST_DIR}/src/s05.c" "${CMAKE_CURRENT_LIST_DIR}/src/s06.c" "${CMAKE_CURRENT_LIST_DIR}/src/s07.c" "${CMAKE_CURRENT_LIST_DIR}/src/s08.c" "${CMAKE_CURRENT_LIST_DIR}/src/s09.c" "${CMAKE_CURRENT_LIST_DIR}/src/s10.c" "${CMAKE_CURRENT_LIST_DIR}/src/pong.c")

set(ZEPHYR_EXTRA_MODULES "${CMAKE_CURRENT_LIST_DIR}/build/zeta")

