# ################################################################# #
#                      FILE GENERATED BY ZetaCLI                    #
#                         DON'T EDIT THIS FILE                      #
# ################################################################# #
message("[ZETA]: Running zeta.cmake")

execute_process(COMMAND zeta gen -b "${CMAKE_CURRENT_LIST_DIR}/build"
                        ${CMAKE_CURRENT_LIST_DIR}/zeta.yaml)

list(APPEND HEADERS "${CMAKE_CURRENT_LIST_DIR}/build/zeta/include/")
list(APPEND SOURCES "${CMAKE_CURRENT_LIST_DIR}/src/ping.c" "${CMAKE_CURRENT_LIST_DIR}/src/pong.c")

set(ZEPHYR_EXTRA_MODULES "${CMAKE_CURRENT_LIST_DIR}/build/zeta")

