/**!
 * @file nb_property_system_callbacks.template.h
 * @author Rodrigo Peixoto (rodrigopex)
 * @brief this file was generated by the nodebee tool.
 *
 * DO NOT EDIT THIS FILE!
 *
 */

#ifndef PDB_CALLBACKS_H_
#define PDB_CALLBACKS_H_

#include "pdb.h"

$services_callbacks

#endif
