/*********************************
 *  FILE GENERATED BY zeta tool  *
 *-------------------------------*
 *                               *
 *  DO NOT EDIT THIS FILE!       *
 *                               *
 *********************************/

/**
 * @file   zeta_threads.template.c
 * @author Lucas Peixoto <lucaspeixotoac@gmail.com>
 *
 * @brief
 *
 *
 */

#include "zeta_threads.h"

#include "zeta.h"

//$services_threads
