/**!
 * @file nb_property_system_validators.template.h
 * @author Rodrigo Peixoto (rodrigopex)
 * @brief this file was generated by the nodebee tool.
 *
 * DO NOT EDIT THIS FILE!
 *
 */

#ifndef PDB_VALIDATORS_H_
#define PDB_VALIDATORS_H_

#include "pdb.h"
#include "validators.def"

#endif
