/**!
 * @file nb_property_system_validators.template.h
 * @author Rodrigo Peixoto (rodrigopex)
 * @brief this file was generated by the nodebee tool.
 *
 * DO NOT EDIT THIS FILE!
 *
 */
#include "pdb.h"
