/**!
 * @file nb_property_system_validators.template.h
 * @author Rodrigo Peixoto (rodrigopex)
 * @brief this file was generated by the nodebee tool.
 *
 * DO NOT EDIT THIS FILE!
 *
 */

#ifndef PDB_VALIDATORS_H_
#define PDB_VALIDATORS_H_

#include "pdb.h"
#include "pdb_validators.def"

int pdb_validator_different_of_zero(u8_t *data, size_t size);

#endif
