/**!
 * @file nb_property_system_validators.template.c
 * @author Rodrigo Peixoto (rodrigopex)
 * @brief this file was generated by the nodebee tool.
 *
 * DO NOT EDIT THIS FILE!
 *
 */
#include "nb_property_system_validators.h"

int nb_binary(u8_t *property_value, size_t size)
{
    NB_UNUSED(size);
    return (0 == property_value[0]) || (1 == property_value[0]);
}
