/**!
 * @file nb_property_system_validators.template.c
 * @author Rodrigo Peixoto (rodrigopex)
 * @brief this file was generated by the nodebee tool.
 *
 * DO NOT EDIT THIS FILE!
 *
 */

#include "pdb_validators.h"

int pdb_validator_different_of_zero(u8_t *data, size_t size) {
    int f = 1;
    for(int i = 0 ; i < size ; ++i) {
        f = f && (data[i] != 0);
    }

    return f;
}
