/* ***************************************************************** */
/*                      FILE GENERATED BY ZetaCLI                    */
/*                         DON'T EDIT THIS FILE                      */
/* ***************************************************************** */

/**
 * @file   zeta_threads.template.h
 * @author Lucas Peixoto <lucaspeixotoac@gmail.com>
 *
 *
 *
 */


#ifndef ZETA_THREADS_H_
#define ZETA_THREADS_H_

#include "zeta.h"

//$services_sections


#endif
