/* ***************************************************************** */
/*                      FILE GENERATED BY ZetaCLI                    */
/*                         DON'T EDIT THIS FILE                      */
/* ***************************************************************** */

/**
 * @file   zeta_callbacks.template.h
 * @author Lucas Peixoto <lucaspeixotoac@gmail.com>
 *
 * @brief  Zeta callbacks header file
 *
 *
 */

#ifndef ZETA_CALLBACKS_H_
#define ZETA_CALLBACKS_H_

#include "zeta.h"

// <ZT_CODE_INJECTION>$services_callbacks// </ZT_CODE_INJECTION>

#endif
