/* ***************************************************************** */
/*                      FILE GENERATED BY ZetaCLI                    */
/*                         DON'T EDIT THIS FILE                      */
/* ***************************************************************** */

/**
 * @file   zeta_custom_functions.template.h
 * @author Lucas Peixoto <lucaspeixotoac@gmail.com>
 *
 * @brief
 *
 *
 */

#ifndef ZETA_CUSTOM_FUNCTIONS_TEMPLATE_H_
#define ZETA_CUSTOM_FUNCTIONS_TEMPLATE_H_

#include "zeta.h"

// <ZT_CODE_INJECTION>$custom_functions// </ZT_CODE_INJECTION>

#endif
