# ################################################################# #
#                      FILE GENERATED BY ZetaCLI                    #
#                         DON'T EDIT THIS FILE                      #
# ################################################################# #
message("[ZETA]: Running zeta.cmake")

execute_process(COMMAND zeta gen -b "$${CMAKE_CURRENT_LIST_DIR}/build"
                        $${CMAKE_CURRENT_LIST_DIR}/zeta.yaml RESULT_VARIABLE ztcli_gen_exit_code)

if (NOT ("${ztcli_gen_exit_code}" STREQUAL "0"))
  message( FATAL_ERROR "ZetaCli generation failed with exit code: ${ztcli_gen_exit_code}")
endif()
                      
list(APPEND HEADERS "$${CMAKE_CURRENT_LIST_DIR}/build/zeta/include/")
list(APPEND SOURCES ${services_sources})

set(ZEPHYR_EXTRA_MODULES "$${CMAKE_CURRENT_LIST_DIR}/build/zeta")

