/* ***************************************************************** */
/*                      FILE GENERATED BY ZetaCLI                    */
/*                         DON'T EDIT THIS FILE                      */
/* ***************************************************************** */

/**
 * @file   zeta_services.template.h
 * @author Lucas Peixoto <lucaspeixotoac@gmail.com>
 *
 *
 *
 */


#ifndef ZETA_SERVICES_H_
#define ZETA_SERVICES_H_

#include "zeta.h"

// <ZT_CODE_INJECTION>$services_reference// </ZT_CODE_INJECTION>


#endif
